# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  ...
}: {
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d70d08e6-4543-4c98-9bd1-d0233c049cca";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/4debecab-c9a4-469e-8edf-9bb048298d42";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d70d08e6-4543-4c98-9bd1-d0233c049cca";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d70d08e6-4543-4c98-9bd1-d0233c049cca";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7E80-8996";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/f9cc0b33-92d4-40bd-aa94-7daa57df537e";
      randomEncryption.enable = true;
    }
  ];
}
