{
  lib,
  pkgs,
  ...
}:
with lib; {
  options = {
    machshev.machineID = mkOption {
      type = types.uniq types.str;
      description = "Machine ID 32 char hex string. Can be generated by dbus-uuidgen.";
    };
  };

  config = {
    programs.direnv.enable = true;
    programs.fish.enable = true;

    fonts.fontDir.enable = true;
    fonts.packages = with pkgs;
      [
        font-awesome
        google-fonts
        meslo-lgs-nf
        corefonts
        vistafonts
      ]
      ++ builtins.filter lib.attrsets.isDerivation (builtins.attrValues
        pkgs.nerd-fonts);

    services.devmon.enable = true;
    services.gvfs.enable = true;
    services.udisks2.enable = true;

    virtualisation.podman = {
      enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };

    # Useful other development tools
    environment.systemPackages = with pkgs; [
      dive # look into docker image layers
      podman-tui # status of containers in the terminal
      podman-compose # start group of containers for dev
      zoom-us
    ];

    virtualisation.libvirtd.enable = true;

    # touchpad support
    services.libinput.enable = true;

    services.xserver.xkb.layout = "us,gb,il";
    services.xserver.xkb.variant = "";

    # Set your time zone.
    time.timeZone = "Europe/London";

    # Select internationalisation properties.
    i18n.defaultLocale = "en_GB.UTF-8";

    i18n.extraLocaleSettings = {
      LC_ADDRESS = "en_GB.UTF-8";
      LC_IDENTIFICATION = "en_GB.UTF-8";
      LC_MEASUREMENT = "en_GB.UTF-8";
      LC_MONETARY = "en_GB.UTF-8";
      LC_NAME = "en_GB.UTF-8";
      LC_NUMERIC = "en_GB.UTF-8";
      LC_PAPER = "en_GB.UTF-8";
      LC_TELEPHONE = "en_GB.UTF-8";
      LC_TIME = "en_GB.UTF-8";
    };
  };
}
